### ISSUE TITLE
Fail to work

### ISSUE THREAD

**Issue by WuVenus** [Syvxx/ECDC#1]
Fail to work
Doesn't seem to work

**Comment by Syvxx** [comment]
![Screenshot 2024-12-05 002556](https://github.com/user-attachments/assets/33cfcf2f-3709-45f1-8f20-7263418c1d0f)


Strange.. did you replace the files inside addon location?

**Comment by WuVenus** [comment]
yes No interface window

**Comment by Syvxx** [comment]
Skickat från min iPhone

5 dec. 2024 kl. 01:54 skrev WuVenus ***@***.***>:

﻿

yes No interface window

**Comment by Syvxx** [comment]
Have you looked under ingame Options>Interface>Addons>ECDC?

5 dec. 2024 kl. 01:54 skrev WuVenus ***@***.***>:

﻿

yes No interface window

**Comment by WuVenus** [comment]
I think that's the problem ECDC.Lua
